name: Check icons

on:
  workflow_call:
    inputs:
      workflows_ref:
        description: 'The current reference in use for the ledger-app-workflow repository'
        required: true
        type: string
      app_repository:
        description: 'The URL of the app repository to check. Defaults to the workflow caller repository URL'
        required: false
        default: ${{ github.repository }}
        type: string
      repo_name:
        description: 'The name of the app repository to check. Defaults to the workflow caller repository name'
        required: false
        default: ${{ github.event.repository.name }}
        type: string
      download_manifest_artifact_name:
        description: 'The name of the artifact containing the built manifest'
        required: true
        type: string
      run_for_devices:
        description: 'The list of device(s) on which the checking will run'
        required: true
        type: string

permissions:
  contents: read  # Needed to clone the repositories

env:
  WORKFLOWS_REF: ${{ inputs.workflows_ref }}
  APP_REPOSITORY: ${{ inputs.app_repository }}
  REPO_NAME: ${{ inputs.repo_name }}
  DOWNLOAD_MANIFEST_ARTIFACT_NAME: ${{ inputs.download_manifest_artifact_name }}
  RUN_FOR_DEVICES: ${{ inputs.run_for_devices }}

jobs:
  handle_inputs:
    name: Handle and validate inputs
    runs-on: ubuntu-latest
    outputs:
      WORKFLOWS_REF: ${{ steps.set_outputs.outputs.WORKFLOWS_REF }}
      APP_REPOSITORY: ${{ steps.set_outputs.outputs.APP_REPOSITORY }}
      REPO_NAME: ${{ steps.set_outputs.outputs.REPO_NAME }}
      DOWNLOAD_MANIFEST_ARTIFACT_NAME: ${{ steps.set_outputs.outputs.DOWNLOAD_MANIFEST_ARTIFACT_NAME }}
      RUN_FOR_DEVICES: ${{ steps.set_outputs.outputs.RUN_FOR_DEVICES }}
    steps:
      - name: Handle Inputs
        id: set_outputs
        run: |
          {
            echo "WORKFLOWS_REF=${WORKFLOWS_REF}"
            echo "APP_REPOSITORY=${APP_REPOSITORY}"
            echo "REPO_NAME=${REPO_NAME}"
            echo "DOWNLOAD_MANIFEST_ARTIFACT_NAME=${DOWNLOAD_MANIFEST_ARTIFACT_NAME}"
            echo "RUN_FOR_DEVICES=${RUN_FOR_DEVICES}"
          } >> "$GITHUB_OUTPUT"

  check_icons:
    name: Check icons
    needs: [handle_inputs]
    strategy:
      fail-fast: false
      matrix:
        device: ${{ fromJSON(inputs.run_for_devices) }}
    runs-on: ubuntu-22.04

    steps:
      - name: Clone ledger-app-workflows repository
        uses: actions/checkout@v4
        with:
          repository: LedgerHQ/ledger-app-workflows
          path: ./ledger-app-workflows
          ref: ${{ needs.handle_inputs.outputs.WORKFLOWS_REF }}

      - name: Clone app repository
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.handle_inputs.outputs.APP_REPOSITORY }}
          path: app-repository
          submodules: recursive

      - name: Download manifest
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.handle_inputs.outputs.DOWNLOAD_MANIFEST_ARTIFACT_NAME }}
          path: ${{ needs.handle_inputs.outputs.DOWNLOAD_MANIFEST_ARTIFACT_NAME }}

      - name: Run script
        run: |
            ./ledger-app-workflows/scripts/check_all.sh -c icons -t ${{ matrix.device }} \
              -a ./app-repository -m ${{ needs.handle_inputs.outputs.DOWNLOAD_MANIFEST_ARTIFACT_NAME }}
