name: Check readme

on:
  workflow_call:
    inputs:
      workflows_ref:
        description: 'The current reference in use for the ledger-app-workflow repository'
        required: true
        type: string
      app_repository:
        description: 'The URL of the app repository to check. Defaults to the workflow caller repository URL'
        required: false
        default: ${{ github.repository }}
        type: string

permissions:
  contents: read  # Needed to clone the repositories

jobs:
  check_readme:
    name: Check readme
    runs-on: ubuntu-22.04

    steps:
      - name: Clone ledger-app-workflows repository
        uses: actions/checkout@v4
        with:
          repository: LedgerHQ/ledger-app-workflows
          path: ./ledger-app-workflows
          ref: ${{ inputs.workflows_ref }}

      - name: Clone app repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.app_repository }}
          path: app-repository
          submodules: recursive

      - name: Run script
        run: |
            ./ledger-app-workflows/scripts/check_all.sh -c readme -a ./app-repository
