---
name: Check SDK submodule version

on:
  workflow_call:

permissions:
  contents: read

jobs:
  warning:
    runs-on: ubuntu-slim
    steps:
      - run: echo "::warning title=Deprecated reusable workflow::Please migrate to this one LedgerHQ/app-ethereum/.github/workflows/check_plugin_sdk.yml@develop"

  delegate:
    uses: LedgerHQ/app-ethereum/.github/workflows/check_plugin_sdk.yml@feat/plugin_sdk_reusable_workflow
