name: Code style check

on:
  workflow_call:
    inputs:
      app_repository:
        description: 'The GIT repository to test (defaults to `github.repository`)'
        required: false
        default: ${{ github.repository }}
        type: string
      app_branch_name:
        description: 'The GIT branch to test (defaults to `github.ref`)'
        required: false
        default: ${{ github.ref }}
        type: string
      run_linter:
        description: "Select the Linter to run (pylint, flake8 or yapf)"
        type: string
        required: true
      run_type_check:
        description: "Whether to run mypy type check (defaults to false)"
        required: true
        type: boolean
      src_directory:
        description: "The directory containing the python sources to check"
        required: true
        type: string
      req_directory:
        description: "The directory containing the requirements.txt (if any)"
        required: false
        default: ''
        type: string
      setup_directory:
        description: "The directory containing the setup.cfg (if any)"
        required: false
        default: ''
        type: string
      additional_packages:
        description: "Additional packages to install (default to none)"
        required: false
        default: ''
        type: string

permissions:
  contents: read

env:
  APP_REPOSITORY: ${{ inputs.app_repository }}
  APP_BRANCH_NAME: ${{ inputs.app_branch_name }}
  RUN_LINTER: ${{ inputs.run_linter }}
  RUN_TYPE_CHECK: ${{ inputs.run_type_check }}
  SRC_DIRECTORY: ${{ inputs.src_directory }}
  REQ_DIRECTORY: ${{ inputs.req_directory }}
  SETUP_DIRECTORY: ${{ inputs.setup_directory }}
  ADDITIONAL_PACKAGES: ${{ inputs.additional_packages }}

jobs:
  handle_inputs:
    name: Handle and validate inputs
    runs-on: ubuntu-latest
    outputs:
      APP_REPOSITORY: ${{ steps.set_outputs.outputs.APP_REPOSITORY }}
      APP_BRANCH_NAME: ${{ steps.set_outputs.outputs.APP_BRANCH_NAME }}
      RUN_LINTER: ${{ steps.set_outputs.outputs.RUN_LINTER }}
      RUN_TYPE_CHECK: ${{ steps.set_outputs.outputs.RUN_TYPE_CHECK }}
      SRC_DIRECTORY: ${{ steps.set_outputs.outputs.SRC_DIRECTORY }}
      REQ_DIRECTORY: ${{ steps.set_outputs.outputs.REQ_DIRECTORY }}
      SETUP_DIRECTORY: ${{ steps.set_outputs.outputs.SETUP_DIRECTORY }}
      ADDITIONAL_PACKAGES: ${{ steps.set_outputs.outputs.ADDITIONAL_PACKAGES }}
    steps:
      - name: Handle Inputs
        id: set_outputs
        run: |
          {
            echo "APP_REPOSITORY=${APP_REPOSITORY}"
            echo "APP_BRANCH_NAME=${APP_BRANCH_NAME}"
            echo "RUN_LINTER=${RUN_LINTER}"
            echo "RUN_TYPE_CHECK=${RUN_TYPE_CHECK}"
            echo "SRC_DIRECTORY=${SRC_DIRECTORY}"
            echo "REQ_DIRECTORY=${REQ_DIRECTORY}"
            echo "SETUP_DIRECTORY=${SETUP_DIRECTORY}"
            echo "ADDITIONAL_PACKAGES=${ADDITIONAL_PACKAGES}"
          } >> "$GITHUB_OUTPUT"

  linter:
    name: Python Linting with ${{ inputs.run_linter }}
    runs-on: ubuntu-latest
    needs: [handle_inputs]
    steps:
      - name: Installing required packages
        if: ${{ needs.handle_inputs.outputs.ADDITIONAL_PACKAGES != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ needs.handle_inputs.outputs.ADDITIONAL_PACKAGES }}

      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.handle_inputs.outputs.APP_REPOSITORY }}
          ref: ${{ needs.handle_inputs.outputs.APP_BRANCH_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Installing Python dependencies
        run: |
          python -m pip install --upgrade pip

          # Install linter
          case "${{ needs.handle_inputs.outputs.RUN_LINTER }}" in
            "pylint") pip install pylint ;;
            "flake8") pip install flake8 flake8-pyproject ;;
            "yapf") pip install yapf ;;
          esac

          # Install project requirements
          if [ -n "${{ needs.handle_inputs.outputs.REQ_DIRECTORY }}" ] && [ -f "${{ needs.handle_inputs.outputs.REQ_DIRECTORY }}/requirements.txt" ]; then
            pip install -r ${{ needs.handle_inputs.outputs.REQ_DIRECTORY }}/requirements.txt
          fi

      - name: Set working directory
        run: |
          if [ -n "${{ needs.handle_inputs.outputs.SETUP_DIRECTORY }}" ]; then
            echo "WORK_DIR=${{ needs.handle_inputs.outputs.SETUP_DIRECTORY }}" >> $GITHUB_ENV
          else
            echo "WORK_DIR=." >> $GITHUB_ENV
          fi

      - name: Run ${{ needs.handle_inputs.outputs.RUN_LINTER }}
        working-directory: ${WORK_DIR}
        run: |
          case "${{ needs.handle_inputs.outputs.RUN_LINTER }}" in
            "pylint")
              ARGS=(-j 0)
              if [ -f "./setup.cfg" ]; then
                ARGS+=(--rcfile "./setup.cfg")
              fi
              pylint "${ARGS[@]}" ${{ needs.handle_inputs.outputs.SRC_DIRECTORY }}
              ;;
            "flake8")
              flake8 ${{ needs.handle_inputs.outputs.SRC_DIRECTORY }}
              ;;
            "yapf")
              yapf ${{ needs.handle_inputs.outputs.SRC_DIRECTORY }} --recursive -d
              ;;
          esac

  mypy:
    name: Type checking
    if: ${{ inputs.run_type_check == true }}
    runs-on: ubuntu-latest
    needs: [handle_inputs]
    steps:
      - name: Installing required packages
        if: ${{ needs.handle_inputs.outputs.ADDITIONAL_PACKAGES != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ needs.handle_inputs.outputs.ADDITIONAL_PACKAGES }}

      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.handle_inputs.outputs.APP_REPOSITORY }}
          ref: ${{ needs.handle_inputs.outputs.APP_BRANCH_NAME }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Installing Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          if [ -n "${{ needs.handle_inputs.outputs.REQ_DIRECTORY }}" ] && [ -f "${{ needs.handle_inputs.outputs.REQ_DIRECTORY }}/requirements.txt" ]; then
            pip install -r ${{ needs.handle_inputs.outputs.REQ_DIRECTORY }}/requirements.txt
          fi

      - name: Set working directory
        run: |
          if [ -n "${{ needs.handle_inputs.outputs.SETUP_DIRECTORY }}" ]; then
            echo "WORK_DIR=${{ needs.handle_inputs.outputs.SETUP_DIRECTORY }}" >> $GITHUB_ENV
          else
            echo "WORK_DIR=." >> $GITHUB_ENV
          fi

      - name: Mypy type checking
        working-directory: ${WORK_DIR}
        run: |
          mypy ${{ needs.handle_inputs.outputs.SRC_DIRECTORY }}
