name: Misspellings checks

on:
  workflow_call:
    inputs:
      app_repository:
        description: 'The GIT repository to test (defaults to `github.repository`)'
        required: false
        default: ${{ github.repository }}
        type: string
      app_branch_name:
        description: 'The GIT branch to test (defaults to `github.ref`)'
        required: false
        default: ${{ github.ref }}
        type: string
      check_filenames:
        description: 'Whether to check filenames for misspellings'
        required: false
        default: true
        type: boolean
      ignore_words_list:
        description: 'Comma-separated list of words to ignore'
        required: false
        default: ''
        type: string
      ignore_words_file:
        description: 'Path to a file containing words to ignore (one per line)'
        required: false
        default: ''
        type: string
      src_path:
        description: 'Comma-separated list of paths to check for misspellings (defaults to all files)'
        required: false
        default: ''
        type: string

permissions:
  contents: read

env:
  APP_REPOSITORY: ${{ inputs.app_repository }}
  APP_BRANCH_NAME: ${{ inputs.app_branch_name }}
  CHECK_FILENAMES: ${{ inputs.check_filenames }}
  IGNORE_WORDS: ${{ inputs.ignore_words_list }}
  IGNORE_WORDS_FILE: ${{ inputs.ignore_words_file }}
  SRC_PATH: ${{ inputs.src_path }}

jobs:
  misspell:
    name: Check misspellings
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.app_repository }}
          ref: ${{ inputs.app_branch_name }}

      - name: Check misspellings
        uses: codespell-project/actions-codespell@v2
        with:
          builtin: clear,rare
          check_filenames: ${{ inputs.check_filenames }}
          ignore_words_list: ${{ inputs.ignore_words_list }}
          ignore_words_file: ${{ inputs.ignore_words_file }}
          path: ${{ inputs.src_path }}
