name: Code style check

on:
  workflow_call:
    inputs:
      run_linter:
        description: "Select the Linter to run (pylint or flake8)"
        type: string
        required: true
        default: ''
      run_type_check:
        description: "Whether to run mypy type check (defaults to false)"
        required: true
        default: false
        type: boolean
      src_directory:
        description: "The directory containing the python sources to check"
        required: true
        default: ''
        type: string
      req_directory:
        description: "The directory containing the requirements.txt (if any)"
        required: false
        default: ''
        type: string
      setup_directory:
        description: "The directory containing the setup.cfg (if any)"
        required: false
        default: ''
        type: string
      additional_packages:
        description: "Additional packages to install (default to none)"
        required: false
        default: ''
        type: string

permissions:
  contents: read

env:
  RUN_LINTER: ${{ inputs.run_linter }}
  RUN_TYPE_CHECK: ${{ inputs.run_type_check }}
  SRC_DIRECTORY: ${{ inputs.src_directory }}
  REQ_DIRECTORY: ${{ inputs.req_directory }}
  SETUP_DIRECTORY: ${{ inputs.setup_directory }}
  ADDITIONAL_PACKAGES: ${{ inputs.additional_packages }}

jobs:
  pylint:
    name: Python Linting with pylint
    if: ${{ inputs.run_linter == 'pylint' }}
    runs-on: ubuntu-latest
    steps:
      - name: Installing required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ${ADDITIONAL_PACKAGES}

      - name: Clone
        uses: actions/checkout@v4

      - name: Installing PIP dependencies
        run: |
          pip install pylint
          if [ -n "${REQ_DIRECTORY}" ] && [ -f "${REQ_DIRECTORY}/requirements.txt" ]; then
            pip install -r ${REQ_DIRECTORY}/requirements.txt
          fi

      - name: Lint Python code
        run: |
          ARGS=(-j 0)
          if [ -n "${SETUP_DIRECTORY}" ]; then
            cd ${SETUP_DIRECTORY}
          fi
          if [ -f "./setup.cfg" ]; then
              ARGS+=(--rcfile "./setup.cfg")
          fi
          pylint "${ARGS[@]}" ${SRC_DIRECTORY}

  flake8:
    name: Python Linting with flake8
    if: ${{ inputs.run_linter == 'flake8' }}
    runs-on: ubuntu-latest
    steps:
      - name: Installing required packages
        run: |
          if [ -n "${ADDITIONAL_PACKAGES}" ]; then
            sudo apt-get update && sudo apt-get install -y ${ADDITIONAL_PACKAGES}
          fi

      - name: Clone
        uses: actions/checkout@v4

      - name: Installing PIP dependencies
        run: |
          pip install flake8 flake8-pyproject
          if [ -n "${REQ_DIRECTORY}" ] && [ -f "${REQ_DIRECTORY}/requirements.txt" ]; then
            pip install -r ${REQ_DIRECTORY}/requirements.txt
          fi

      - name: Lint Python code
        run: |
          if [ -n "${SETUP_DIRECTORY}" ]; then
            cd ${SETUP_DIRECTORY}
          fi
          flake8 ${SRC_DIRECTORY}

  mypy:
    name: Type checking
    if: ${{ inputs.run_type_check == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Installing required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ${ADDITIONAL_PACKAGES}

      - name: Clone
        uses: actions/checkout@v4

      - name: Installing PIP dependencies
        run: |
          pip install mypy
          if [ -n "${REQ_DIRECTORY}" ] && [ -f "${REQ_DIRECTORY}/requirements.txt" ]; then
            pip install -r ${REQ_DIRECTORY}/requirements.txt
          fi

      - name: Mypy type checking
        run: |
          if [ -n "${SETUP_DIRECTORY}" ]; then
            cd ${SETUP_DIRECTORY}
          fi
          mypy ${SRC_DIRECTORY}
