name: Unit testing with Codecov coverage checking and upload the result

on:
  workflow_call:
    inputs:
      app_repository:
        description: 'The GIT repository to test (defaults to `github.repository`)'
        required: false
        default: ${{ github.repository }}
        type: string
      app_branch_name:
        description: 'The GIT branch to test (defaults to `github.ref`)'
        required: false
        default: ${{ github.ref }}
        type: string
      test_directory:
        description: "The directory containing the unit-tests to run"
        required: true
        type: string
      builder:
        description: "The docker image to build the application in (defaults to ledger-app-builder-lite)"
        required: false
        default: 'ledger-app-builder-lite'
        type: string
      additional_packages:
        description: "Additional APT packages to install (default to none)"
        required: false
        default: ''
        type: string

permissions:
  contents: read
  actions: write  # For upload-artifact

env:
  APP_REPOSITORY: ${{ inputs.app_repository }}
  APP_BRANCH_NAME: ${{ inputs.app_branch_name }}
  TEST_DIRECTORY: ${{ inputs.test_directory }}
  BUILDER: ${{ inputs.builder }}
  ADDITIONAL_PACKAGES: ${{ inputs.additional_packages }}

jobs:
  handle_inputs:
    name: Handle and validate inputs
    runs-on: ubuntu-latest
    outputs:
      APP_REPOSITORY: ${{ steps.set_outputs.outputs.APP_REPOSITORY }}
      APP_BRANCH_NAME: ${{ steps.set_outputs.outputs.APP_BRANCH_NAME }}
      TEST_DIRECTORY: ${{ steps.set_outputs.outputs.TEST_DIRECTORY }}
      BUILDER: ${{ steps.set_outputs.outputs.BUILDER }}
      ADDITIONAL_PACKAGES: ${{ steps.set_outputs.outputs.ADDITIONAL_PACKAGES }}
    steps:
      - name: Handle Inputs
        id: set_outputs
        run: |
          {
            echo "APP_REPOSITORY=${APP_REPOSITORY}"
            echo "APP_BRANCH_NAME=${APP_BRANCH_NAME}"
            echo "TEST_DIRECTORY=${TEST_DIRECTORY}"
            echo "BUILDER=${BUILDER}"
            echo "ADDITIONAL_PACKAGES=${ADDITIONAL_PACKAGES}"
          } >> "$GITHUB_OUTPUT"

  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [handle_inputs]
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/${{ needs.handle_inputs.outputs.BUILDER }}:latest

    steps:
      - name: Installing required packages
        run: |
          if [ -n "${{ needs.handle_inputs.outputs.ADDITIONAL_PACKAGES }}" ]; then
            apt install --no-install-recommends -y ${{ needs.handle_inputs.outputs.ADDITIONAL_PACKAGES }}
          fi

      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.handle_inputs.outputs.APP_REPOSITORY }}
          ref: ${{ needs.handle_inputs.outputs.APP_BRANCH_NAME }}
          submodules: recursive
          token: ${{ secrets.token && secrets.token || github.token }}

      - name: Set working directory
        run: |
          if [ -n "${{ needs.handle_inputs.outputs.TEST_DIRECTORY }}" ]; then
            echo "WORK_DIR=${{ needs.handle_inputs.outputs.TEST_DIRECTORY }}" >> $GITHUB_ENV
          else
            echo "WORK_DIR=." >> $GITHUB_ENV
          fi

      - name: Build unit tests
        working-directory: ${WORK_DIR}
        run: |
          cmake -Bbuild -H. && make -C build

      - name: Run unit tests
        working-directory: ${WORK_DIR}
        run: |
          CTEST_OUTPUT_ON_FAILURE=1 make -C build test

      - name: Generate code coverage
        working-directory: ${WORK_DIR}
        run: |
          lcov --directory . -b "$(realpath build/)" --capture --initial -o coverage.base
          lcov --rc lcov_branch_coverage=1 --directory . -b "$(realpath build/)" --capture -o coverage.capture
          lcov --directory . -b "$(realpath build/)" --add-tracefile coverage.base --add-tracefile coverage.capture -o coverage.info
          lcov --directory . -b "$(realpath build/)" --remove coverage.info "*/${{ needs.handle_inputs.outputs.TEST_DIRECTORY }}/*" -o coverage.info
          genhtml coverage.info -o coverage

      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: ${{ needs.handle_inputs.outputs.TEST_DIRECTORY }}/coverage

      - name: Install codecov dependencies
        run: apt install --no-install-recommends -y curl gpg

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.codecov_token }}
        with:
          files: ./${{ needs.handle_inputs.outputs.TEST_DIRECTORY }}/coverage.info
          flags: unittests
          name: codecov-${{ needs.handle_inputs.outputs.APP_REPOSITORY }}
          fail_ci_if_error: true
          verbose: true
